spring:
  application:
    name: tremane-backend
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tremane}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: 3
      minimum-idle: 1
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 10000

  messages:
    basename: messages
    encoding: UTF-8

resend:
  api-key: ${RESEND_API_KEY:}
  api-url: ${RESEND_API_URL:https://api.resend.com/emails}
  from-address: "${RESEND_FROM_ADDRESS:TREMANE <noreply@tremane.click>}"

app:
  universal-link-base-url: ${APP_UNIVERSAL_LINK_BASE_URL:https://tremane-dev.web.app}

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chibitaka.tremane_backend.entity
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.chibitaka.tremane_backend.typehandler
