spring:
  application:
    name: tremane-backend

  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/tremane}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  messages:
    basename: messages
    encoding: UTF-8
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.chibitaka.tremane_backend.entity
  configuration:
    map-underscore-to-camel-case: true
  type-handlers-package: com.chibitaka.tremane_backend.typehandler
